"""Install Cursor assets + index Explorer for FastAPI projects."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from livespec_mcp.config import REPO_CONFIG_FILENAME, load_repo_config
from livespec_mcp.explorer.autowire import autowire_fastapi_explorer, find_fastapi_entrypoints


@dataclass(frozen=True)
class FastapiInitResult:
    workspace: str
    indexed: bool
    explorer_bundle: bool
    autowire: dict[str, object]
    cursor_rule: str | None
    cursor_skill: str | None
    session_prompt: str | None
    fastapi_entry: str | None
    errors: tuple[str, ...]


def _templates_root() -> Path:
    return Path(resources.files("livespec_mcp")) / "templates" / "fastapi"


def _ensure_livespec_toml(workspace: Path) -> None:
    path = workspace / REPO_CONFIG_FILENAME
    if path.is_file():
        return
    path.write_text(
        "# Generated by livespec-mcp fastapi init\n"
        "[explorer]\n"
        "auto_mount = true\n"
        'mount_path = "/explorer"\n',
        encoding="utf-8",
    )


def _install_cursor_assets(workspace: Path) -> tuple[str | None, str | None, str | None]:
    root = _templates_root()
    rule_src = root / "cursor" / "rules" / "livespec-fastapi.mdc"
    skill_src = root / "cursor" / "skills" / "livespec-fastapi"
    prompt_src = root / "SESSION_PROMPT.md"

    rule_dest = workspace / ".cursor" / "rules" / "livespec-fastapi.mdc"
    skill_dest = workspace / ".cursor" / "skills" / "livespec-fastapi"
    prompt_dest = workspace / ".livespec" / "SESSION_PROMPT.md"

    rule_dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(rule_src, rule_dest)
    if skill_dest.exists():
        shutil.rmtree(skill_dest)
    shutil.copytree(skill_src, skill_dest)

    prompt_text = prompt_src.read_text(encoding="utf-8").replace(
        "WORKSPACE", str(workspace.resolve())
    )
    prompt_dest.parent.mkdir(parents=True, exist_ok=True)
    prompt_dest.write_text(prompt_text, encoding="utf-8")

    return str(rule_dest), str(skill_dest), str(prompt_dest)


def init_fastapi_project(
    workspace: Path | str,
    *,
    index: bool = True,
    wire_app: bool = True,
    install_cursor: bool = True,
) -> FastapiInitResult:
    """Index + Explorer bundle + optional autowire + Cursor rule/skill."""
    root = Path(workspace).resolve()
    if not root.is_dir():
        raise FileNotFoundError(f"Not a directory: {root}")

    errors: list[str] = []
    _ensure_livespec_toml(root)
    cfg = load_repo_config(root)

    indexed = False
    explorer_bundle = False
    autowire_payload: dict[str, object] = {"wired": False, "reason": "skipped"}

    entries = find_fastapi_entrypoints(root)
    fastapi_entry = str(entries[0][0].relative_to(root)) if entries else None

    if index:
        try:
            from livespec_mcp.state import get_state
            from livespec_mcp.tools.indexing import _maybe_regenerate_explorer, run_index_pipeline

            st = get_state(str(root), create=True)
            run_index_pipeline(st, force=False, embed=False)
            indexed = True
            explorer_bundle = _maybe_regenerate_explorer(st, explorer=True)
            if not explorer_bundle:
                from livespec_mcp.tools.explorer import write_explorer_bundle

                write_explorer_bundle(st)
                explorer_bundle = True
        except Exception as e:
            errors.append(f"index: {e}")

    if wire_app and cfg.explorer_auto_mount and entries:
        try:
            aw = autowire_fastapi_explorer(
                root,
                auto_mount=True,
                mount_path=cfg.explorer_mount_path,
            )
            autowire_payload = {
                "wired": aw.wired or aw.reason == "already_wired",
                "file": aw.file,
                "app_var": aw.app_var,
                "reason": aw.reason,
                "mount_path": cfg.explorer_mount_path,
            }
        except Exception as e:
            errors.append(f"autowire: {e}")
    elif not entries:
        autowire_payload = {"wired": False, "reason": "no_fastapi_entrypoint"}
    else:
        autowire_payload = {"wired": False, "reason": "auto_mount_disabled"}

    rule_path = skill_path = prompt_path = None
    if install_cursor:
        try:
            rule_path, skill_path, prompt_path = _install_cursor_assets(root)
        except Exception as e:
            errors.append(f"cursor: {e}")

    return FastapiInitResult(
        workspace=str(root),
        indexed=indexed,
        explorer_bundle=explorer_bundle or (root / ".mcp-docs" / "explorer" / "index.html").is_file(),
        autowire=autowire_payload,
        cursor_rule=rule_path,
        cursor_skill=skill_path,
        session_prompt=prompt_path,
        fastapi_entry=fastapi_entry,
        errors=tuple(errors),
    )
