#!/usr/bin/env python3
"""Print a markdown PR comment summarising Spec impact for a git range.

Uses the same ``compute_diff_spec_impact`` helper as the Spec Explorer
Changes view. Intended for GitHub Actions (``livespec-pr-comment.yml``) but
runnable locally:

    uv run python scripts/pr_diff_impact.py
    GITHUB_BASE_SHA=main GITHUB_HEAD_SHA=HEAD uv run python scripts/pr_diff_impact.py

Environment:
    LIVESPEC_WORKSPACE — project root (default: cwd)
    GITHUB_BASE_SHA / GITHUB_HEAD_SHA — git range (default: main..HEAD)
    LIVESPEC_BASE_REF / LIVESPEC_HEAD_REF — fallbacks when SHA vars unset
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


def _env_ref(primary: str, fallback: str, default: str) -> str:
    return os.environ.get(primary) or os.environ.get(fallback) or default


def _pct(ratio: float) -> str:
    return f"{round(ratio * 100)}%"


def render_markdown(
    *,
    base: str,
    head: str,
    files_changed: list[str],
    specs_touched: list[dict],
    workspace: Path,
) -> str:
    """Build the PR comment body."""
    lines: list[str] = [
        "## Livespec — Spec impact",
        "",
        f"**Range:** `{base}`..`{head}`  ",
        f"**Workspace:** `{workspace}`",
        "",
    ]
    if not files_changed:
        lines.extend(
            [
                "No changed files in this range (or workspace is not indexed).",
                "",
            ]
        )
        return "\n".join(lines)

    lines.append(f"**{len(files_changed)}** file(s) changed.")
    lines.append("")
    if not specs_touched:
        lines.extend(
            [
                "No tracked specs are touched by these changes.",
                "",
                "<details><summary>Changed files</summary>",
                "",
            ]
        )
        lines.extend(f"- `{p}`" for p in files_changed[:50])
        if len(files_changed) > 50:
            lines.append(f"- … and {len(files_changed) - 50} more")
        lines.append("")
        lines.append("</details>")
        lines.append("")
        return "\n".join(lines)

    lines.append(
        f"**{len(specs_touched)}** spec(s) touched:"
    )
    lines.append("")
    lines.append("| Spec | Title | Test coverage | Changed files |")
    lines.append("|---|---|---:|---|")
    for row in specs_touched:
        spec_id = row.get("spec_id", "")
        title = (row.get("title") or "").replace("|", "\\|")
        cov = _pct(float(row.get("test_coverage_ratio") or 0))
        files = row.get("files") or []
        file_cell = ", ".join(f"`{f}`" for f in files[:5])
        if len(files) > 5:
            file_cell += f" (+{len(files) - 5} more)"
        lines.append(f"| `{spec_id}` | {title} | {cov} | {file_cell or '—'} |")
    lines.append("")
    under_tested = [
        r
        for r in specs_touched
        if float(r.get("test_coverage_ratio") or 0) < 0.5
    ]
    if under_tested:
        ids = ", ".join(f"`{r['spec_id']}`" for r in under_tested[:12])
        lines.append(f"> **Heads-up:** low test coverage on {ids}.")
        lines.append("")
    lines.append(
        "_Generated by [livespec](https://github.com/Rixmerz/livespec) "
        "`scripts/pr_diff_impact.py`_"
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    workspace = Path(os.environ.get("LIVESPEC_WORKSPACE", ".")).resolve()
    base = _env_ref("GITHUB_BASE_SHA", "LIVESPEC_BASE_REF", "main")
    head = _env_ref("GITHUB_HEAD_SHA", "LIVESPEC_HEAD_REF", "HEAD")

    from livespec_mcp.state import get_state
    from livespec_mcp.tools.analysis import compute_diff_spec_impact
    from livespec_mcp.tools.indexing import run_index_pipeline

    # create=True because the very next line IS the indexing step. Without it
    # `get_state` raises WorkspaceNotIndexedError telling the caller to index
    # first — on a CI runner that has never indexed, which is every PR run, so
    # this job could not reach `run_index_pipeline` to build the index that
    # `get_state` was demanding. `create` gates first creation only; the state
    # it returns is the same one the pipeline then populates.
    st = get_state(str(workspace), create=True)
    run_index_pipeline(st, force=False)

    impact = compute_diff_spec_impact(st, base, head)
    body = render_markdown(
        base=str(impact.get("base") or base),
        head=str(impact.get("head") or head),
        files_changed=list(impact.get("files_changed") or []),
        specs_touched=list(impact.get("specs_touched") or []),
        workspace=workspace,
    )
    sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
